language: python

services:
    - docker

before_install:
    - docker build -t soren/olivar-container .

script:
    - docker run soren/olivar-container

after_success:
    # Push the image back to Docker Hub
    - docker login -u $D_USERNAME -p $D_PASSWORD
    - docker push soren/olivar-container

